### ISSUE TITLE
NullPointerException when LZ4Factory is loaded by bootstrap class loader

### ISSUE THREAD

**Issue by yilongli** [jpountz/lz4-java#59]
At https://github.com/jpountz/lz4-java/blob/aef24cfbbf53d6ade60073b287edc610be743e43/src/java/net/jpountz/lz4/LZ4Factory.java#L149, ```LZ4Factory.class.getClassLoader()``` might return null if ```LZ4Factory``` is loaded by the bootstrap class loader. It results in a NPE.

```LZ4Factory``` is loaded by the bootstrap class loader in my application because I am using lz4 in a Java agent and this Java agent is loaded by the bootstrap class loader.

**Comment by trask** [comment]
+1

**Comment by jpountz** [comment]
Closing as I merged https://github.com/jpountz/lz4-java/pull/60
