### ISSUE TITLE
Some of the java classses are not found it says when excuting code.

### ISSUE THREAD

**Issue by bjambu20** [jpountz/lz4-java#67]
Some of the java classses are not found it says when excuting code. 
ie) net.jpountz.lz4.LZ4JavaSafeCompressor not found and other classes. Please tell me to resolve these issues.

**Comment by jpountz** [comment]
Is it a custom build or an official release? Part of the ant build generates java classes including the one you are missing, I suspect that you built manually instead of using the Ant build as described in the README.
